version: '2.1'
services:

  #
  # janus-gateway
  #
  janus-gateway:
    logging:
      driver: syslog
      options:
        syslog-address: "udp://logs4.papertrailapp.com:30889"

    network_mode: host
    image: 'canyan/janus-gateway:0.9.2'
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    ports:
      - "8188:8188"
      - "8088:8088"
      - "8089:8089"
      - "8889:8889"
      - "8000:8000"
      - "7088:7088"
      - "7089:7089"
      - "10000-10200:10000-10200/udp"
    volumes:
      - "./janus_configs/janus.jcfg:/usr/local/etc/janus/janus.jcfg"
      - "./janus_configs/janus.plugin.videoroom.jcfg:/usr/local/etc/janus/janus.plugin.videoroom.jcfg"
      - "/home/ubuntu/janus_recordings:/home/ubuntu/janus_recordings"
    restart: always
